# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 94f091ca95a0d07ec9c2235997670fd805c6cf7f9d00a69b4d9b58bf0362afd629bfd628d2d893720a1bab1355d5df368314468e567570148a833e80215e3e1f

test:
  secret_key_base: cb97b682e33baeb9bad661861d8758a4c3738e5deab69e85b4d2ba9036889a8366c5622e656278b9d83e405c82b26b96e01f74e0800f97257adfac13d4f53394

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
